version: '3'

# Hadoop Cluster
x-hadoop-variables:
  common: &hadoop-common
    image: data-infra:hadoop
    build:
      context: hadoop
      dockerfile: dockerfile
  master: &hadoop-master
    depends_on:
      - zk-1
      - zk-2
      - zk-3
      - hdp-worker-1
      - hdp-worker-2
      - hdp-worker-3
  worker: &hadoop-worker
    command: ["start-hdp-worker.sh"]

x-hadoop-cluster: &hadoop-cluster
  hdp-master-1:
    <<: [ *hadoop-common, *hadoop-master ]
    container_name: hdp-master-1
    hostname: hdp-master-1
    command: ["start-hdp-master.sh", "active"]
    ports:
      - "9870:9870" # nn web-ui
      - "8088:8088" # yarn rm web-ui
      # - "9868:9868" # secondary nn web-ui (for single nn)

  hdp-master-2:
    <<: [ *hadoop-common, *hadoop-master ]
    container_name: hdp-master-2
    hostname: hdp-master-2
    command: ["start-hdp-master.sh", "standby"]
    ports:
      - "9871:9870" # nn web-ui
      - "8089:8088" # yarn rm web-ui

  hdp-master-3:
    <<: [ *hadoop-common, *hadoop-master ]
    container_name: hdp-master-3
    hostname: hdp-master-3
    command: ["start-hdp-manager.sh"]
    ports:
      - "19888:19888" # job history server web-ui

  hdp-worker-1:
    <<: [ *hadoop-common, *hadoop-worker ]
    container_name: hdp-worker-1
    hostname: hdp-worker-1

  hdp-worker-2:
    <<: [ *hadoop-common, *hadoop-worker ]
    container_name: hdp-worker-2
    hostname: hdp-worker-2

  hdp-worker-3:
    <<: [ *hadoop-common, *hadoop-worker ]
    container_name: hdp-worker-3
    hostname: hdp-worker-3

# Zookeeper Cluster
x-zookeeper-variables:
  common: &zookeeper-common
    image: zookeeper:3.8.3
    restart: on-failure
  environment: &zookeeper-environment # https://hub.docker.com/_/zookeeper
    ZOO_PORT: 2181
    ZOO_SERVERS: >
      server.1=zk-1:2888:3888;2181
      server.2=zk-2:2888:3888;2181
      server.3=zk-3:2888:3888;2181
    ZOO_INIT_LIMIT: 10
    ZOO_SYNC_LIMIT: 5
    ZOO_TICK_TIME: 2000
    ZOO_DATA_DIR: /data

x-zookeeper-cluster: &zookeeper-cluster
  zk-1:
    <<: *zookeeper-common
    container_name: zk-1
    hostname: zk-1
    environment:
      ZOO_MY_ID: 1
      <<: *zookeeper-environment

  zk-2:
    <<: *zookeeper-common
    container_name: zk-2
    hostname: zk-2
    environment:
      ZOO_MY_ID: 2
      <<: *zookeeper-environment

  zk-3:
    <<: *zookeeper-common
    container_name: zk-3
    hostname: zk-3
    environment:
      ZOO_MY_ID: 3
      <<: *zookeeper-environment

# Hive cluster
x-hive-cluster: &hive-cluster
  hive-1:
    <<: *hadoop-common
    container_name: hive-1
    hostname: hive-1
    command: ["start-hdp-hive.sh"]
    ports:
      # - "9083:9083" # metastore
      # - "10000:10000" # hiverserver2
      - "10002:10002" # hiveserver2 web-ui
    depends_on:
      - mariadb


# SERVICES
services:
  <<: [
    *zookeeper-cluster,
    *hadoop-cluster,
    *hive-cluster,
  ]
  # Database
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:11.1
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mariadb-admin", "-uroot", "-proot", "ping" ]
      interval: 5s
      retries: 5
    ports:
      - "3306:3306"

# networks:
#   default:
#     ipam:
#       config:
#         - subnet: 255.255.255.0
