FROM nvcr.io/nvidia/tritonserver:24.01-py3

# Deps
RUN apt update && apt install -y git wget

WORKDIR /tmp

RUN wget https://cmake.org/files/v3.28/cmake-3.28.3-linux-x86_64.tar.gz
RUN git clone https://github.com/speechmatics/ctranslate2_triton_backend.git && cd ctranslate2_triton_backend
RUN git clone --recursive https://github.com/OpenNMT/CTranslate2.git

WORKDIR /opt/tritonserver

# CMake
RUN mkdir /opt/cmake-3.28 && \
    tar --strip-components=1 -xz -C /opt/cmake-3.28 -f /tmp/cmake-3.28.3-linux-x86_64.tar.gz
ENV PATH=/opt/cmake-3.28/bin:$PATH

# Intel OneAPI
RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \ | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
RUN apt update && apt install -y intel-basekit

# CTranslate2
# RUN ln -sf $(which python3) /usr/bin/python
# RUN pip install ctranslate2
RUN mkdir /tmp/CTranslate2/build && \
    cd /tmp/CTranslate2/build && \
    cmake .. && \
    make -j4 && \
    make install

# CTranslate2 Backend
RUN apt update && apt install -y rapidjson-dev
RUN mkdir /tmp/ctranslate2_triton_backend/build && \
    cd /tmp/ctranslate2_triton_backend/build && \
    cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DTRITON_ENABLE_GPU=1 \
        -DCMAKE_INSTALL_PREFIX=/opt/tritonserver/backends/ctranslate2 && \
    make install
# RUN mv -rvf /tmp/ctranslate2_triton_backend/build/install /opt/tritonserver/backends/ctranslate2
