ARG ES_VERSION=x.y.z

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
ARG ES_VERSION

# Install plugins
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch analysis-nori # nori-analyzer
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch repository-s3 # backup to S3
# RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack # x-pack (installed by default)

USER root

# Metricbeat
COPY ./assets/metricbeat-${ES_VERSION}-amd64.deb /tmp
RUN dpkg -i /tmp/metricbeat-${ES_VERSION}-amd64.deb && \
    metricbeat modules enable elasticsearch-xpack
COPY ./config/metricbeat/metricbeat.yml /etc/metricbeat/
COPY ./config/metricbeat/elasticsearch-xpack.yml /etc/metricbeat/modules.d/

# Filebeat
# This is just for example!! (Docker elasticsearch doesn't make log file, except garbage collection)
COPY ./assets/filebeat-${ES_VERSION}-amd64.deb /tmp
RUN dpkg -i /tmp/filebeat-${ES_VERSION}-amd64.deb && \
    filebeat modules enable elasticsearch
COPY ./config/filebeat/filebeat.yml /etc/filebeat/
COPY ./config/filebeat/elasticsearch.yml /etc/filebeat/modules.d/

# Run Service
USER elasticsearch
# COPY scripts/init-es.sh .
# ENTRYPOINT [ "/bin/tini", "--", "./init-es.sh"]

# CMD service metricbeat start && \
#     service filebeat start && \
#     /usr/local/bin/docker-entrypoint.sh