FROM python:3.8

WORKDIR /tmp
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

WORKDIR /opt/app
COPY ./app .
COPY ./scripts/* /usr/sbin/

CMD ["start-server.sh"]
