http.host: "0.0.0.0"
path.config: /usr/share/logstash/config/logstash.conf

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts:
  - http://elasticsearch:9200

# Use 'logstash_system' as username rather than 'elastic' in production,
# after setting passwords in elasticsearch
xpack.monitoring.elasticsearch:
  username: "elastic"
  password: "elastic"